-- 코드를 입력하세요
WITH TABLE1 AS 
(SELECT CAR_ID, MONTH(START_DATE) AS MONTH
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE MONTH(START_DATE) > 7 AND MONTH(START_DATE) < 11 AND YEAR(START_DATE) = 2022)

SELECT MONTH, CAR_ID, COUNT(MONTH) AS RECORDS
FROM TABLE1
WHERE CAR_ID IN (SELECT CAR_ID FROM TABLE1
                 GROUP BY CAR_ID
                 HAVING COUNT(CAR_ID) > 4)
GROUP BY CAR_ID, MONTH
ORDER BY MONTH ASC, CAR_ID DESC