-- 15:20
SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(USER_ID) >= 2
ORDER BY USER_ID ASC, PRODUCT_ID DESC

# SELECT ONLINE_SALE_ID, USER_ID, PRODUCT_ID
# FROM ONLINE_SALE
# ORDER BY USER_ID, PRODUCT_ID

-- 15 12 / 119 12