-- 코드를 입력하세요
WITH ANIMAL_INTACT_INS AS (
    SELECT ANIMAL_ID,
        ANIMAL_TYPE,
        NAME
    FROM ANIMAL_INS
    WHERE REPLACE(REPLACE(SEX_UPON_INTAKE, ' Female', ''), ' Male', '') = 'Intact'
), ANIMAL_INTACT_OUTS AS (
    SELECT ANIMAL_ID,
        ANIMAL_TYPE,
        NAME
    FROM ANIMAL_OUTS
    WHERE ANIMAL_ID IN (SELECT AII.ANIMAL_ID FROM ANIMAL_INTACT_INS AS AII) AND
        REPLACE(REPLACE(SEX_UPON_OUTCOME, ' Female', ''), ' Male', '') != 'Intact'
)
SELECT AIO.ANIMAL_ID AS ANIMAL_ID,
    AIO.ANIMAL_TYPE AS ANIMAL_TYPE,
    AIO.NAME AS NAME
FROM ANIMAL_INTACT_OUTS AS AIO
