-- 15:43
SELECT REST_INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO JOIN REST_REVIEW ON REST_INFO.REST_ID = REST_REVIEW.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_INFO.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC

# SELECT REVIEW_ID, REST_NAME, REVIEW_SCORE
# FROM REST_INFO, REST_REVIEW
# WHERE SUBSTRING(ADDRESS, 1, 5) = '서울특별시' AND REST_INFO.REST_ID = REST_REVIEW.REST_ID

# SELECT *
# FROM REST_INFO
# WHERE SUBSTRING(ADDRESS, 1, 5) = '서울특별시'
# 1,5,8