-- 2021년에 가입한 회원들 중 상품을 구매한 회원수와 상품을 구매한 회원의 비율을 년, 월 별로 출력
WITH USERS_JOINED_2021 AS (
    SELECT U.user_id as user_id
    FROM USER_INFO AS U
    WHERE YEAR(JOINED) = 2021
), USER_PERCHASE_COUNT AS (
    SELECT YEAR(OS.SALES_DATE) AS `YEAR`,
        MONTH(OS.SALES_DATE) AS `MONTH`,
        COUNT(DISTINCT(UJ.user_id)) AS PURCHASED_USERS
    FROM USERS_JOINED_2021 AS UJ
        JOIN ONLINE_SALE AS OS
        ON UJ.user_id = OS.user_id
    GROUP BY `YEAR`, `MONTH`
)
SELECT UP.YEAR AS `YEAR`,
    UP.MONTH AS `MONTH`,
    UP.PURCHASED_USERS AS PURCHASED_USERS,
    ROUND(UP.PURCHASED_USERS / (SELECT COUNT(*) FROM USERS_JOINED_2021) , 1) AS PUCHASED_RATIO
FROM USER_PERCHASE_COUNT AS UP
ORDER BY `YEAR` ASC, `MONTH` ASC