-- 15:31
SELECT ITEM_ID AS ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT ITEM_TREE.ITEM_ID
    FROM ITEM_INFO, ITEM_TREE
    WHERE RARITY = 'RARE' AND ITEM_INFO.ITEM_ID = PARENT_ITEM_ID
)
ORDER BY ITEM_ID DESC